name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Stelle sicher, dass die Node-Version angegeben ist

      - name: Install dependencies
        run: npm install
        working-directory: ./react-frontend # Setze das Arbeitsverzeichnis

      - name: Build project
        run: npm run build
        working-directory: ./react-frontend # Setze das Arbeitsverzeichnis

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./react-frontend/dist # Setze das korrekte Verzeichnis

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./react-frontend/dist # Setze das korrekte Verzeichnis

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react-frontend/dist # Setze das korrekte Verzeichnis